apiVersion: kubedirector.hpe.com/v1beta1
kind: KubeDirectorApp
metadata:
  name: dataikudss604
spec:
  label:
    name: Dataiku DSS 6.0.4
    description: Dataiku DSS 6.0.4 on centos 7.x
  distroID: dzinsouhpe/dataikudss
  version: '6.0.4'
  configSchemaVersion: 7
  services:
  - id: ssh
    label:
      name: SSH
    endpoint:
      port: 22
      isDashboard: false
  - id: dss
    label:
      name: DSS
    endpoint:
      port: 11000
      urlScheme: http
      isDashboard: false
  roles:
  - id: dssnode
    cardinality: "1"
    imageRepoTag: docker.io/dzinsouhpe/dataikudss:latest
  config:
    selectedRoles:
    - dssnode
    roleServices:
    - roleID: dssnode
      serviceIDs:
      - ssh
      - dss
  systemdRequired: true
  defaultPersistDirs:
  - /opt/dataiku/data
